### ISSUE TITLE
Open to a more permissive license?

### ISSUE THREAD

**Issue by TheButlah** [GothAck/FlatRPC#12]
The MIT license is a lot more permissive. Would that be ok to use instead of GPL?

**Comment by GothAck** [comment]
What benefits would both you and I gain from MIT over GPL?
I'd really like to see bugfixes and changes up-streamed into the project as much as possible, which is part of the reason I leaned towards GPL.

**Comment by GothAck** [comment]
Would LGPL be a good compromise? I'm moving towards dynamic linking anyways

**Comment by TheButlah** [comment]
I know that at my company at least we only use MIT and Apache. In my experience, people are more likely to use your code if they are sure it won't cause legal problems, and as a result you are more likely to get PRs and contributions that way

**Comment by GothAck** [comment]
Seems fair, I'll update my license branch and merge it into master

**Comment by GothAck** [comment]
Project is now licensed under the MIT license
