### ISSUE TITLE
Recent flatbuffers commit breaks use of shared_ptr.

### ISSUE THREAD

**Issue by GothAck** [GothAck/FlatRPC#13]
https://github.com/google/flatbuffers/commit/54f8b787cbdac587b1c9fec1ffe5a2ad2f0d61a2

Gonna have to use a custom smart ptr. Fun.

**Comment by GothAck** [comment]
Issue opened upstream https://github.com/google/flatbuffers/issues/5813

**Comment by vglavnyy** [comment]
The `_o` is the local (invisible) object. Why you need `shared_ptr` here?
Who and how can it share?

Before the 54f8b78:
```cpp
inline MonsterT *Monster::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  auto _o = new MonsterT();
  UnPackTo(_o, _resolver); // _o is MonsterT*
  return _o;
}
```

After the 54f8b78:
```cpp
auto _o = flatbuffers::unique_ptr<MyGame::Sample::MonsterT>(new MonsterT());
UnPackTo(_o.get(), _resolver); // _o.get() returns MonsterT*
return _o.release(); // release local object std::unique_ptr<MonsterT>
```

**Comment by GothAck** [comment]
Using --cpp-ptr-type std::shared_ptr --cpp-std c++17 causes _o.release() to be invalid, let me get an example.

**Comment by GothAck** [comment]
Building with latest flatbuffers flatc for this repo ends up throwing:
```
➜  build git:(examples_as_integrations) ✗ make
[  1%] Generating rpc_generated.h
Scanning dependencies of target rpc_fbs
[  2%] Linking CXX static library librpc_fbs.a
[  2%] Built target rpc_fbs
[  4%] Generating include/flatrpc/rpcversion.hpp
Scanning dependencies of target flatrpc-static
[  5%] Building CXX object rpc/CMakeFiles/flatrpc-static.dir/rpcbase.cpp.o
In file included from /home/gothack/workspace/c++/flatrpc/rpc/include/flatrpc/rpcbase.hpp:16,
                 from /home/gothack/workspace/c++/flatrpc/rpc/rpcbase.cpp:7:
/home/gothack/workspace/c++/flatrpc/build/rpc/fbs/rpc_generated.h: In member function ‘flatrpc::rpc::ExceptionT* flatrpc::rpc::Exception::UnPack(const resolver_function_t*) const’:
/home/gothack/workspace/c++/flatrpc/build/rpc/fbs/rpc_generated.h:334:13: error: ‘class std::shared_ptr<flatrpc::rpc::ExceptionT>’ has no member named ‘release’
  334 |   return _o.release();
```

**Comment by GothAck** [comment]
I've commented here https://github.com/google/flatbuffers/commit/54f8b787cbdac587b1c9fec1ffe5a2ad2f0d61a2#r37847947

**Comment by vglavnyy** [comment]
Oh.. I see. Thank you for the report.
`flatbuffers::unique_ptr<MyGame::Sample::MonsterT>` isn't true `unique_ptr`.
This pointer depends on `--cpp-ptr-type` option.

**Comment by GothAck** [comment]
Aye, that template parameter will use whatever is passed as --cpp-ptr-type, just happens to be a unique_ptr by default.

**Comment by GothAck** [comment]
Commit 0186bd1 reverts to using default unique_ptr from flatc, no ill effects detected

**Comment by GothAck** [comment]
Closing this issue,  but will keep an eye on the upstream issue, as I kinda like using shared_ptr with flatbuffers, but this project will no longer have that requirement.
